name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t myapp:latest ./myapp

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from Docker Hub
        run: |
          docker pull wadeed/shs:tagname

      - name: Tag the image
        run: |
          docker tag wadeed/shs:tagname myapp:latest

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl

      - name: Start Minikube
        run: |
          minikube start

      - name: Set up kubectl context
        run: |
          kubectl config use-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl create deployment myapp --image=myapp:latest
          kubectl expose deployment myapp --type=NodePort --port=8080

      - name: Check deployment status
        run: |
          kubectl get deployment myapp
          kubectl get pods
